# Generated by Django 3.1.5 on 2021-01-19 15:26

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_auto_20210111_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='callboard.category', verbose_name='Родитель'),
        ),
    ]
